# Generated by Django 3.0.6 on 2020-05-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='flat',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='house',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
