# Generated by Django 3.0.6 on 2020-05-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200529_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
