# Generated by Django 3.0.6 on 2020-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remote',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
