# Generated by Django 3.0.6 on 2020-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
