# Generated by Django 3.0.6 on 2020-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.CharField(default='/media/images/default.png', max_length=255),
        ),
    ]
